import { Exchange } from "../generated/prisma/enums.js";

export const stocks = [
  {
    symbol: "RELIANCE",
    name: "Reliance Industries",
    logoUrl: "https://ui-avatars.com/api/?name=RELIANCE&size=256",
    exchange: Exchange.NSE,
    listingPrice: "2500",
  },
  {
    symbol: "TCS",
    name: "Tata Consultancy Services",
    logoUrl: "https://ui-avatars.com/api/?name=TCS&size=256",
    exchange: Exchange.NSE,
    listingPrice: "3200",
  },
  {
    symbol: "INFY",
    name: "Infosys",
    logoUrl: "https://ui-avatars.com/api/?name=INFY&size=256",
    exchange: Exchange.NSE,
    listingPrice: "1500",
  },
  {
    symbol: "HDFCBANK",
    name: "HDFC Bank",
    logoUrl: "https://ui-avatars.com/api/?name=HDFCBANK&size=256",
    exchange: Exchange.NSE,
    listingPrice: "1600",
  },
  {
    symbol: "ICICIBANK",
    name: "ICICI Bank",
    logoUrl: "https://ui-avatars.com/api/?name=ICICIBANK&size=256",
    exchange: Exchange.NSE,
    listingPrice: "950",
  },
  {
    symbol: "SBIN",
    name: "State Bank of India",
    logoUrl: "https://ui-avatars.com/api/?name=SBIN&size=256",
    exchange: Exchange.NSE,
    listingPrice: "600",
  },
  {
    symbol: "ITC",
    name: "ITC Ltd",
    logoUrl: "https://ui-avatars.com/api/?name=ITC&size=256",
    exchange: Exchange.NSE,
    listingPrice: "450",
  },
  {
    symbol: "LT",
    name: "Larsen & Toubro",
    logoUrl: "https://ui-avatars.com/api/?name=LT&size=256",
    exchange: Exchange.NSE,
    listingPrice: "2900",
  },
  {
    symbol: "AXISBANK",
    name: "Axis Bank",
    logoUrl: "https://ui-avatars.com/api/?name=AXISBANK&size=256",
    exchange: Exchange.NSE,
    listingPrice: "1100",
  },
  {
    symbol: "MARUTI",
    name: "Maruti Suzuki",
    logoUrl: "https://ui-avatars.com/api/?name=MARUTI&size=256",
    exchange: Exchange.NSE,
    listingPrice: "9000",
  },

  // ===== NASDAQ =====
  {
    symbol: "AAPL",
    name: "Apple Inc",
    logoUrl: "https://ui-avatars.com/api/?name=AAPL&size=256",
    exchange: Exchange.NASDAQ,
    listingPrice: "150",
  },
  {
    symbol: "MSFT",
    name: "Microsoft Corp",
    logoUrl: "https://ui-avatars.com/api/?name=MSFT&size=256",
    exchange: Exchange.NASDAQ,
    listingPrice: "280",
  },
  {
    symbol: "GOOGL",
    name: "Alphabet Inc",
    logoUrl: "https://ui-avatars.com/api/?name=GOOGL&size=256",
    exchange: Exchange.NASDAQ,
    listingPrice: "2700",
  },
  {
    symbol: "AMZN",
    name: "Amazon Inc",
    logoUrl: "https://ui-avatars.com/api/?name=AMZN&size=256",
    exchange: Exchange.NASDAQ,
    listingPrice: "3300",
  },
  {
    symbol: "META",
    name: "Meta Platforms",
    logoUrl: "https://ui-avatars.com/api/?name=META&size=256",
    exchange: Exchange.NASDAQ,
    listingPrice: "220",
  },
  {
    symbol: "TSLA",
    name: "Tesla Inc",
    logoUrl: "https://ui-avatars.com/api/?name=TSLA&size=256",
    exchange: Exchange.NASDAQ,
    listingPrice: "700",
  },
  {
    symbol: "NFLX",
    name: "Netflix",
    logoUrl: "https://ui-avatars.com/api/?name=NFLX&size=256",
    exchange: Exchange.NASDAQ,
    listingPrice: "500",
  },
  {
    symbol: "NVDA",
    name: "NVIDIA",
    logoUrl: "https://ui-avatars.com/api/?name=NVDA&size=256",
    exchange: Exchange.NASDAQ,
    listingPrice: "250",
  },
  {
    symbol: "ADBE",
    name: "Adobe",
    logoUrl: "https://ui-avatars.com/api/?name=ADBE&size=256",
    exchange: Exchange.NASDAQ,
    listingPrice: "550",
  },
  {
    symbol: "INTC",
    name: "Intel",
    logoUrl: "https://ui-avatars.com/api/?name=INTC&size=256",
    exchange: Exchange.NASDAQ,
    listingPrice: "45",
  },
];
